kan-262 changed export dialog title options
cameronsutter/plottr_electron pull request #556
Opened 2021-03-30 16:13 UTC by jeanawhou

![Screenshot from 2021-03-31 00-09-23](https://user-images.githubusercontent.com/19387007/113020886-9e8bc400-91b5-11eb-9892-4af5d6158080.png)
Just changing the export dialog title

task link: https://app.ora.pm/p/4c35de9a18594ccbaee3377dcc546780?v=0&t=k&c=f8bf4b5874fa44498cb5f5b0de430468

2021-03-31 02:47 UTC, murfdog64 approved these changes

2021-03-31 11:14 UTC, Quiescent requested changes
Looks good :)

Please could you change the translation too?
You can use the npm scripts in `lib/plottr_locales` to synchronise changes between `en.json`, `es.json` and `fr.json`.
When you've made the change, please be sure to submit a PR to https://github.com/Plotinator/plottr_locales using:
`git subtree push --prefix=lib/plottr_locales plottr_locales feature/kan-262`.
If you don't have `plottr_locales` as a remote, then you can add it with:
`git remote add plottr_locales git@github.com:Plotinator/plottr_locales.git`

2021-04-06 08:51 UTC, Quiescent commented
> Looks good :)
> 
> Please could you change the translation too?
> You can use the npm scripts in `lib/plottr_locales` to synchronise changes between `en.json`, `es.json` and `fr.json`.
> When you've made the change, please be sure to submit a PR to https://github.com/Plotinator/plottr_locales using:
> `git subtree push --prefix=lib/plottr_locales plottr_locales feature/kan-262`.
> If you don't have `plottr_locales` as a remote, then you can add it with:
> `git remote add plottr_locales git@github.com:Plotinator/plottr_locales.git`

@jeanawhou I merged the other PR, now you either need to:
 - push up the commit that you made to this branch as well,  or
 - pull down plottr_locales.
 
 I'd recommend the first option.

2021-04-06 22:30 UTC, cameronsutter approved these changes

2021-04-22 07:19 UTC, Quiescent approved these changes
Upstream has the changes :+1:

2021-04-22 07:20 UTC, merged