remove tags from card, character, note, places when tag is deleted
cameronsutter/plottr_electron pull request #685
Opened 2021-06-29 15:15 UTC by jeanawhou

ticket link: https://app.ora.pm/p/320746?c=5230103
Sorry about the low resolution

preview
https://user-images.githubusercontent.com/19387007/123823198-8dc32980-d92f-11eb-83eb-bba505b04475.mp4

2021-06-30 07:29 UTC, Quiescent commented on lib/plottr_components/src/components/tag/TagView.js
> +    removeTags = (tagId) => {
This isn't the right place to remove those tags.
The DELETE_TAG action should be handled in the `cards`, `characters`, `notes` and `places` reducers, where we can remove tags from each of those pieces of state.
(In an ideal world, our components would have no logic in them except for highly dynamic/interesting UI display stuff).

2021-06-30 07:42 UTC, Quiescent commented
Good job on the thorough testing!
Let's just move the logic to the reducers and then we can get this merged :)

2021-07-01 15:23 UTC, Quiescent commented on lib/plottr_components/src/components/tag/TagView.js
> +    removeTags = (tagId) => {
This is nearly it.  The next step is to only have one action to delete a tag.
That action can go into the tags actions file.
You only need to call that one action and the `DELETE_TAG` event with the tag's `id` will reach all the reducers.

2021-07-02 13:43 UTC, cameronsutter commented
You're on the right path. Like what Ed is saying, you shouldn't need to create any new actions. The `deleteTag` action in actions/tags.js already fires a DELETE_TAG event. So the only change needed should be to change the cards/characters/places/notes reducers to handle the DELETE_TAG event

2021-07-02 13:44 UTC, cameronsutter requested changes
You're on the right path. Like what Ed is saying, you shouldn't need to create any new actions. The `deleteTag` action in actions/tags.js already fires a DELETE_TAG event. So the only change needed should be to change the cards/characters/places/notes reducers to handle the DELETE_TAG event

2021-07-05 08:07 UTC, Quiescent approved these changes
Looks good.  LGTM!

2021-07-05 08:08 UTC, merged