Bugfix/import scrivener
cameronsutter/plottr_electron pull request #785
Opened 2022-04-18 07:22 UTC by jeanawhou

@Quiescent @cameronsutter I added the ability to accept characters, places and tags from cards/notes.rtf and also fix the contenating values for the RCE.

I will added the demo on the #desktop-devs channel 😅

2022-04-18 08:49 UTC, Quiescent commented on lib/plottr_import_export/src/importer/scrivener/importer.js
> +function getManuscriptSectionItems(currentJson, RTFContents, bookId) {
This function needs tests.
It's riddled with assumptions and heuristics, and we must verify that it works as we intended it to.

2022-04-18 08:52 UTC, Quiescent commented on lib/plottr_import_export/src/importer/scrivener/importer.js
> +function filterRTFContents(RTFContents) {
This function needs tests and a better name.
The name should describe the intention, not the function we called on `RTFContents`.
How about `keepNonDuplicatedNonEmptyText` ?
Also: what if a user repeats a line verbatim?

2022-04-18 09:13 UTC, Quiescent requested changes
Good work.

Before we go ahead and merge this: the functionality in `importer.js` is very complicated, and you are now *the* person with a complete understanding of it.
Given:
 a) how important this feature is, and
 b) how complicated the logic is,
I'm going to insist that you add unit tests for every function in this file.

2022-04-29 10:45 UTC, jeanawhou commented
@Quiescent @cameronsutter i added a unit test for all the functions in scrivener importer except for the functions with file handling. I've copied the jsonified example3.scriv and that's what i used to create the tests. Should i also add unit test for file handling?

2022-04-29 10:47 UTC, Quiescent commented
> @Quiescent @cameronsutter i added a unit test for all the functions in scrivener importer except for the functions with file handling. I've copied the jsonified example3.scriv and that's what i used to create the tests. Should i also add unit test for file handling?

I'm taking a look.  In principle, I'm fine with not unit testing the file handling. :+1:

2022-04-29 11:00 UTC, Quiescent commented on lib/plottr_import_export/src/importer/scrivener/__tests__/importer.test.js
> +      expect(isAnObject(storyLines)).toBeTruthy()
Is there any assertion we can make about the members of the object?
i.e. does it look like RCE content?
If it does, then it would be useful to verify that it has the right members as well as being an object.

2022-04-29 11:05 UTC, Quiescent commented on lib/plottr_import_export/src/importer/scrivener/__tests__/importer.test.js
> +      expect(typeof newLine).toBe('number')
Does the line id change between test runs?
If not, perhaps we should check that it's a specific number.

2022-04-29 11:32 UTC, Quiescent commented
This PR was a massive undertaking.  Thank you for putting in those tests! :raised_hands:
Please see the two minor comments I had.

2022-05-01 16:17 UTC, jeanawhou commented
@Quiescent @cameronsutter PR updated

2022-05-02 05:04 UTC, Quiescent approved these changes

2022-05-02 05:05 UTC, Quiescent approved these changes
LGTM!

2022-05-02 05:05 UTC, merged